name: homes_repository
description: My new Flutter package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_generator: ^2.0.0
  oxidized: ^6.2.0
  path_provider: ^2.1.5
  rxdart: ^0.28.0

dev_dependencies:
  build_runner: ^2.4.10
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0