name: homes_repository
description: My new Flutter package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  oxidized: ^6.2.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^3.0.3
  very_good_analysis: ^6.0.0
